# frozen_string_literal: true

# Autogenerated file

SimpleCov.start 'rails' do
  refuse_coverage_drop
end

# if ENV['CODECOV_TOKEN']
#   require 'codecov'
#   SimpleCov.formatter = SimpleCov::Formatter::Codecov
# end

Rails.application.eager_load! if defined?(Spring) && ENV['DISABLE_SPRING'].nil?
