# frozen_string_literal: true

# Autogenerated file

if ENV['COVERAGE']
  require 'simplecov'

  SimpleCov.start 'rails'

  if ENV['CODECOV_TOKEN']
    require 'codecov'
    SimpleCov.formatter = SimpleCov::Formatter::Codecov
  end
end
